theme: jekyll-theme-minimal
title: Alyssia's homepage
description: Eco pixel game for syn1

lsi: false
safe: true
source: Syn_Project3_climate_Routine
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
